<a href="https://colab.research.google.com/github/donib-irakihda/fusemachines-ai-fellowship/blob/main/linear_regression__from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt

def featureNormalization(X):
  X_mean = np.mean(X, axis = 0)
  X_std = np.std(X, axis=0)
  X_normalized = np.zeros((X.shape[0], X.shape[1]))

  for x in range(0, X.shape[0]):
    for y in range(0, X.shape[1]):
      normalized_value = (X[x,y]-X_mean[y])/X_std[y]
      X_normalized[x,y] = normalized_value
  return X_normalized, X_mean, X_std

X = np.array([[1.30,2.21,3.23,4.12], [1.56, 6.23, 6.34, 9.23], [0.11, 0.92, 3.84, 0.18]])
X_normalized, X_mean, X_std = featureNormalization(X)
print(X_normalized)
print(X_mean)
print(X_std)


[[ 0.49109521 -0.40242644 -0.92156595 -0.1052653 ]
 [ 0.90298151  1.37532553  1.3897809   1.27398003]
 [-1.39407672 -0.97289909 -0.46821496 -1.16871473]]
[0.99 3.12 4.47 4.51]
[0.63124216 2.26128282 1.34553583 3.70492465]


In [5]:
def applyNormalization(X, X_mean, X_std):
  X_normalized = np.zeros((X.shape[0], X.shape[1]))
  for x in range(0, X.shape[0]):
    for y in range(0, X.shape[1]):
      normalized_value = (X[x,y]-X_mean[y])/X_std[y]
      X_normalized[x,y] = normalized_value

  return X_normalized

X = np.array([[1.30,2.21,3.23,4.12], [1.56, 6.23, 6.34, 9.23], [0.11, 0.92, 3.84, 0.18]])
X_mean = np.array([1.0, 1.0, 2.0, 0.1])
X_std = np.array([1.0, 1.0, 2.0, 0.1])
X_normalized = applyNormalization(X, X_mean, X_std)
print(X_normalized)

[[ 3.00e-01  1.21e+00  6.15e-01  4.02e+01]
 [ 5.60e-01  5.23e+00  2.17e+00  9.13e+01]
 [-8.90e-01 -8.00e-02  9.20e-01  8.00e-01]]
